sprites.onOverlap(SpriteKind.Player, SpriteKind.Projectile, function (sprite, otherSprite) {
    game.over(false)
})
sprites.onDestroyed(SpriteKind.Projectile, function (sprite) {
    info.changeScoreBy(1)
})
let projectile: Sprite = null
let mySprite = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    .........fffff..........
    .......ffb1111ff........
    ......fb1111111bf.......
    ......f111111111f.......
    .....ffff1111111df......
    ....fb111c1dd111df......
    ....ffb1b1fdcf11bf......
    .....ffbfbfb11111f......
    ......ffffcfdb1b1f......
    .......fcccfcfbfbf......
    ........ffffffffff......
    .........ffffff.........
    .........ffffff.........
    .....f..fffffff.........
    .....fffffffff..........
    ......fffffff...........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
controller.moveSprite(mySprite, 0, 50)
mySprite.x = 8
mySprite.setStayInScreen(true)
info.setScore(0)
game.onUpdateInterval(500, function () {
    projectile = sprites.createProjectileFromSide(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . 2 3 3 3 2 2 2 . . . . . 
        . . . 2 3 1 1 1 1 1 3 3 2 2 2 . 
        . . . 2 1 1 1 1 1 1 1 1 1 1 1 . 
        . . . 2 3 1 1 1 1 1 3 3 2 2 2 . 
        . . . . 2 3 3 3 3 2 2 . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, -150, 0)
    projectile.setPosition(scene.screenWidth(), randint(0, scene.screenHeight()))
    if (info.score() < 10) {
        projectile.vx += 100
    }
})
